# config.yml
ai:
  prompt: "Respond to the following question based solely on the provided data. Maintain the tone and voice of Don Beyer, using the first person. Do not include any phrases like 'as a member of Congress' or 'visit my website.'"

  model: "gpt-4o"

  settings:
    temperature: 0.5
    #max_tokens: 150
    #top_p: 1.0
    frequency_penalty: 0.5
    presence_penalty: 0.0

options:
    response:
      - name: "1 Minute"
        prompt: "Provide a response that would take about 1 minute to speak aloud."
        about: "A 1-minute spoken response with inference."

      - name: "30 Seconds"
        prompt: "Provide a response that would take about 30 seconds to speak aloud."
        about: "A 30-second concise spoken response."

      - name: "Concise"
        prompt: "Provide a concise response in no more than two sentences, excluding any unnecessary information."
        about: "The most direct answer possible."

      - name: "Detailed"
        prompt: "Provide a detailed and comprehensive response."
        about: "An in-depth and thorough answer."

      - name: "Speculative"
        prompt: "Provide a concise response based on the provided information, and include any reasonable inferences or assumptions."
        about: "Includes reasonable inferences and assumptions."

      - name: "No Inference"
        prompt: "Provide a response based strictly on the provided data without any inferences. If the answer is not found, state that directly."
        about: "Strictly based on data, no inferences."
