# docker-compose.local-only.yml
# A completely independent Docker Compose setup for local-only services

services:
  db_postgres:
    container_name: db_postgres
    hostname: db_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - cgpt-data:/var/lib/postgresql/data
    networks:
      - candidategpt
    #  - cloud-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:5432

  langfuse:
    container_name: langfuse
    hostname: langfuse
    image: langfuse/langfuse:latest
    restart: always
    depends_on:
      db_postgres:
        condition: service_healthy
    environment:
      SALT: ${LANGFUSE_SALT}
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD:  ${POSTGRES_PASSWORD}
      DATABASE_NAME: langfuse
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PORT: ${LANGFUSE_PORT}
      SMTP_CONNECTION_URL: ${SMTP_CONNECTION_URL}
      EMAIL_FROM_ADDRESS: ${SMTP_SENDER_EMAIL}
      LANGFUSE_LOG_LEVEL: ${LOG_LEVEL}
      # Setup
      LANGFUSE_INIT_ORG_ID: ${LANGFUSE_INIT_ORG_ID}
      LANGFUSE_INIT_ORG_NAME: ${LANGFUSE_INIT_ORG_NAME}
      LANGFUSE_INIT_PROJECT_ID: ${LANGFUSE_INIT_PROJECT_ID}
      LANGFUSE_INIT_PROJECT_NAME: ${LANGFUSE_INIT_PROJECT_NAME}
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      LANGFUSE_INIT_PROJECT_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY}
      LANGFUSE_INIT_USER_EMAIL: ${LANGFUSE_INIT_USER_EMAIL}
      LANGFUSE_INIT_USER_NAME: ${LANGFUSE_INIT_USER_NAME}
      LANGFUSE_INIT_USER_PASSWORD: ${LANGFUSE_INIT_USER_PASSWORD}
    ports:
      - ${LANGFUSE_PORT}:${LANGFUSE_PORT}
    networks:
      - candidategpt

networks:
  candidategpt:
    driver: bridge

volumes:
  cgpt-data:
