

services:
# This is ROUGH and mostly for my servers, I'll have a better one later... or  feel free to submit a pr :)

  db_postgres:
    container_name: db_postgres
    hostname: db_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${MNT_PATH}:/var/lib/postgresql/data
    networks:
      - datasystems
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:5432



  candidategpt:
    container_name: candidategpt
    hostname: candidategpt
    image: ghcr.io/henselforcongress/candidategpt:latest
    restart: always
    volumes:
      - ${LOG_PATH}:/logs
    env_file: stack.env
    depends_on:
      - db_postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - datasystems
      - cloud-net
    command: ["/entrypoint.sh", "python3", "-m", "run"]

# https://langfuse.com/docs/deployment/self-host
  langfuse:
    container_name: langfuse
    hostname: langfuse
    image: langfuse/langfuse:latest
    restart: always
    environment:
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD:  ${POSTGRES_PASSWORD}
      DATABASE_NAME: langfuse
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PORT: ${LANGFUSE_PORT}
      SMTP_CONNECTION_URL: ${SMTP_CONNECTION_URL}
      EMAIL_FROM_ADDRESS: ${SMTP_SENDER_EMAIL}
      LANGFUSE_LOG_LEVEL: ${LOG_LEVEL}
      LANGFUSE_INIT_USER_EMAIL: ${LANGFUSE_INIT_USER_EMAIL}






networks:
  datasystems:
    external: true
  cloud-net:
    external: true

