# docker compose -f docker-compose-litellm.yml up -d
# docker compose --litellm docker-compose-litellm.yml down -v

name: litellm

services:

    litellm:
        image: ghcr.io/berriai/litellm:main-stable
        container_name: litellm
        hostname: litellm
        ports:
          - 4000:4000
        environment:
            DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
            STORE_MODEL_IN_DB: "True"
            LITELLM_MASTER_KEY: "sk-1234"
            LITELLM_SALT_KEY: "sk-1234"
        networks:
          - candidategpt

    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: litellm
          POSTGRES_USER: llmproxy
          POSTGRES_PASSWORD: dbpassword9090
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
          interval: 1s
          timeout: 5s
          retries: 10
        networks:
          - candidategpt

networks:
    candidategpt:
      driver: bridge
